# -*- coding: utf-8 -*-
"""mycurvefit-definition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sms8xlyNWM65F0uSuMh1hvinD9s-HBS1
"""

!pip install uncertainties
from uncertainties import ufloat
import uncertainties as um
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit


def mycurvefit(func,XX,YY,UNCERT,xlabel=None,ylabel=None,p0=None):
    
    # To get curve_fit to use UNCERT, set absolute_sigma = True.  Otherwise sigma = 1
    fitparams,pcov = curve_fit(func,XX,YY,sigma = UNCERT,absolute_sigma=True, p0=p0)

    # Find error in each parameter.  Assumes covariance matrix is roughly diagonal.
    fiterrs = np.sqrt(np.diag(pcov))

    # print out the parameters and errors on them 
    print('Best Fit Parameters:')
    i = 0
    for A,sigA in zip(fitparams, fiterrs):
        i = i + 1
        mystring = '\t P' + str(i) + ' = '
        print(mystring,round(A,2),'+/-',round(sigA,2))
    

    #### print 'slope' and 'y-intercept' instead
    mystring = '\t ' + 'slope' + ' = '
    print(mystring,round(fitparams[0],5),'+/-',round(fiterrs[0],5))

    mystring = '\t ' + 'y-intercept' + ' = '
    print(mystring,round(fitparams[1],5),'+/-',round(fiterrs[1],5))

    ##################################################
    #                Begin Plotting                  #
    ##################################################
    
    fig,ax = plt.subplots()
    # plot the raw data
    ax.errorbar(XX,YY,UNCERT,fmt='.',label='data')
    
    
    # plot the fit
    XX_shade = np.linspace(min(XX),max(XX),100)
    ax.plot(XX_shade,func(XX_shade,*fitparams),label = 'best fit')
    
    if xlabel == None:
      xlabel = ''
    if ylabel == None:
      ylabel = ''

    # make the plot nice
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    plt.legend()
    
    return fitparams,fiterrs

## next, let's define our line() function using descriptive param names
def line(xdata, slope, yintercept):
  return slope*xdata+yintercept
